import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';
import 'package:sub3/models/telemetry.dart';
import 'package:sub3/services/fit_generator.dart';

/// Independent verification of the FIT encoder: the generated bytes are
/// decoded with python-fitparse — a decoder that shares no code with
/// fit_tool and validates the file header and CRC on parse — and the
/// decoded messages are asserted against the telemetry that went in.
///
/// Skips with a clear message when the decoder environment is missing, so
/// CI without /tmp/fitenv still passes.
const _python = '/tmp/fitenv/bin/python';

/// Prints every message as JSON, grouped by message name. fitparse applies
/// each field's scale/offset, so speed arrives in m/s and altitude in
/// metres — but positions stay raw semicircles, which is exactly what the
/// test wants to check.
const _decodeScript = '''
import json, sys
from fitparse import FitFile

out = {}
for m in FitFile(sys.argv[1]).get_messages():
    row = {}
    for d in m:
        v = d.value
        row[d.name] = v.isoformat() if hasattr(v, "isoformat") else v
    out.setdefault(m.name, []).append(row)
print(json.dumps(out))
''';

/// `deg × 2^31 / 180` is how FIT stores positions; invert it to compare
/// the decoded semicircles against the input degrees.
double _semicirclesToDegrees(num semicircles) =>
    semicircles * 180 / math.pow(2, 31);

DateTime _utc(String isoNoZone) => DateTime.parse('${isoNoZone}Z');

Future<Map<String, dynamic>> _decode(String path) async {
  final result = await Process.run(_python, ['-c', _decodeScript, path]);
  expect(result.exitCode, 0,
      reason: 'fitparse rejected the file: ${result.stderr}');
  return jsonDecode(result.stdout as String) as Map<String, dynamic>;
}

void main() {
  final decoderAvailable = File(_python).existsSync();

  group('fitparse decodes the generated FIT (§1)', () {
    late Directory tmp;

    setUp(() {
      tmp = Directory.systemTemp.createTempSync('sub3_fit_decode');
    });

    tearDown(() {
      if (tmp.existsSync()) tmp.deleteSync(recursive: true);
    });

    test('virtual run: sport, records, positions, totals', () async {
      final startTime = DateTime.utc(2026, 8, 23, 1, 2, 3);
      final telemetry = List.generate(5, (i) {
        return TelemetryPoint(
          elapsedSeconds: i,
          heartRate: 140.0 + i,
          cadence: 80 + i,
          speedKmh: 12.0 + i * 0.1,
          inclinePct: 1.0,
          cumulativeDistanceKm: i * 0.0033,
          latitude: 1.3521 + i * 0.0001,
          longitude: 103.8198 + i * 0.0001,
          altitude: 15.0 + i * 0.5,
        );
      });

      final path = '${tmp.path}/virtual_run.fit';
      File(path).writeAsBytesSync(FitGenerator.generate(
        startTime: startTime,
        telemetry: telemetry,
        totalDistanceM: 13.2,
        totalTimeSeconds: 5,
        elevationGainM: 2.4,
      ));

      final decoded = await _decode(path);

      // The pair that makes Strava file the upload as a Virtual Run.
      final session = (decoded['session'] as List).single;
      expect(session['sport'], 'running');
      expect(session['sub_sport'], 'virtual_activity');
      expect(session['start_time'], '2026-08-23T01:02:03');
      expect(session['total_elapsed_time'], 5.0);
      expect(session['total_timer_time'], 5.0);
      expect(session['total_distance'], closeTo(13.2, 0.01));
      expect(session['total_ascent'], 2);
      expect(session['avg_heart_rate'], 142);
      expect(session['max_heart_rate'], 144);
      // With sport=running, fitparse resolves the cadence subfield name.
      expect(session['avg_running_cadence'], 82);
      expect(session['first_lap_index'], 0);
      expect(session['num_laps'], 1);
      // Bookkeeping fields Garmin recommends, mirroring FTP4 exactly.
      expect(session['message_index'], 0);
      expect(session['event'], 'session');
      expect(session['event_type'], 'stop');

      final lap = (decoded['lap'] as List).single;
      expect(lap['start_time'], '2026-08-23T01:02:03');
      expect(lap['total_elapsed_time'], 5.0);
      expect(lap['total_timer_time'], 5.0);
      expect(lap['total_distance'], closeTo(13.2, 0.01));
      expect(lap['avg_heart_rate'], 142);
      expect(lap['max_heart_rate'], 144);
      expect(lap['avg_cadence'], 82);
      expect(lap['message_index'], 0);
      expect(lap['event'], 'lap');
      expect(lap['event_type'], 'stop');

      final records = decoded['record'] as List;
      expect(records.length, telemetry.length);

      // Positions survive the semicircle round trip.
      for (final pair in [
        (records.first, telemetry.first),
        (records.last, telemetry.last),
      ]) {
        final (record, point) = pair;
        expect(_semicirclesToDegrees(record['position_lat'] as num),
            closeTo(point.latitude!, 1e-5));
        expect(_semicirclesToDegrees(record['position_long'] as num),
            closeTo(point.longitude!, 1e-5));
      }

      // Speed within 0.01 m/s; heart rate and cadence exact; altitude within
      // FIT's 0.2 m resolution.
      for (var i = 0; i < records.length; i++) {
        final record = records[i] as Map<String, dynamic>;
        final point = telemetry[i];
        expect(record['speed'], closeTo(point.speedKmh / 3.6, 0.01));
        expect(record['heart_rate'], point.heartRate!.round());
        expect(record['cadence'], point.cadence);
        expect(record['altitude'], closeTo(point.altitude!, 0.2));
        expect(record['distance'],
            closeTo(point.cumulativeDistanceKm * 1000, 0.01));
      }

      // Timestamps: first == startTime (UTC), strictly monotonic at 1 Hz.
      final times =
          records.map((r) => _utc(r['timestamp'] as String)).toList();
      expect(times.first, startTime);
      for (var i = 1; i < times.length; i++) {
        expect(times[i].isAfter(times[i - 1]), isTrue,
            reason: 'record timestamps must be monotonic');
      }
    });

    test('structured workout: no position, synthesized altitude exported',
        () async {
      final startTime = DateTime.utc(2026, 8, 23, 22, 30, 0);
      final telemetry = List.generate(4, (i) {
        return TelemetryPoint(
          elapsedSeconds: i,
          heartRate: 150.0,
          cadence: 85,
          speedKmh: 10.0,
          inclinePct: 2.0,
          cumulativeDistanceKm: i * 0.0028,
          altitude: 5.0 + i * 0.1,
        );
      });

      final path = '${tmp.path}/workout.fit';
      File(path).writeAsBytesSync(FitGenerator.generate(
        startTime: startTime,
        telemetry: telemetry,
        totalDistanceM: 8.4,
        totalTimeSeconds: 4,
        elevationGainM: 0.3,
      ));

      final decoded = await _decode(path);

      final session = (decoded['session'] as List).single;
      expect(session['sport'], 'running');
      expect(session['sub_sport'], 'virtual_activity');
      expect(session['total_ascent'], 0); // 0.3 m rounds to 0

      final records = decoded['record'] as List;
      expect(records.length, telemetry.length);
      for (var i = 0; i < records.length; i++) {
        final record = records[i] as Map<String, dynamic>;
        expect(record.containsKey('position_lat'), isFalse);
        expect(record.containsKey('position_long'), isFalse);
        expect(record['altitude'], closeTo(telemetry[i].altitude!, 0.2));
        expect(record['heart_rate'], 150);
        expect(record['cadence'], 85);
      }
      expect(_utc((records.first as Map)['timestamp'] as String), startTime);
    });

    test('a longitude near +180° survives instead of decoding as the '
        'invalid sentinel', () async {
      // 179.9999999° would round to semicircle 0x7FFFFFFF — the sint32
      // "invalid" sentinel, which fitparse decodes as None — so the
      // generator wraps it to −180°, the same meridian.
      final path = '${tmp.path}/antimeridian.fit';
      File(path).writeAsBytesSync(FitGenerator.generate(
        startTime: DateTime.utc(2026, 8, 23, 1, 2, 3),
        telemetry: const [
          TelemetryPoint(
            elapsedSeconds: 0,
            speedKmh: 12.0,
            inclinePct: 0.0,
            cumulativeDistanceKm: 0,
            latitude: -54.8019,
            longitude: 179.9999999,
          ),
        ],
        totalDistanceM: 0,
        totalTimeSeconds: 1,
        elevationGainM: 0,
      ));

      final decoded = await _decode(path);
      final record = (decoded['record'] as List).single as Map;
      expect(record['position_long'], -2147483648,
          reason: 'the longitude must wrap to −180°, not vanish');
      expect(_semicirclesToDegrees(record['position_lat'] as num),
          closeTo(-54.8019, 1e-5));
    });
  },
      skip: decoderAvailable
          ? false
          : 'Python decoder missing at /tmp/fitenv — create it with fitparse '
              'installed to run the independent FIT verification.');
}
